export type VideoProps = {
  didJustFinish: false;
  durationMillis: 5400;
  hasJustBeenInterrupted: false;
  isBuffering: false;
  isLoaded: true;
  isLooping: true;
  isMuted: false;
  isPlaying: false;
  pitchCorrectionQuality: "Varispeed";
  playableDurationMillis: 5400;
  positionMillis: 0;
  progressUpdateIntervalMillis: 500;
  rate: 1;
  shouldCorrectPitch: false;
  shouldPlay: false;
  target: 597;
  uri: "https://res.cloudinary.com/dfayz3rrm/video/upload/v1708220079/soph/b5j9866j8e317qzh0hpv.mp4";
  volume: 1;
};
